---
version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPOSITORY_URI: 691778449106.dkr.ecr.us-east-1.amazonaws.com/nginx-app-repo

phases:
  install:
    commands:
      - echo Checking Docker
      - docker --version

      - echo Checking zip
      - zip --version

  pre_build:
    commands:
      - echo Logging into Amazon ECR
      - |
        aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

  build:
    commands:
      - echo Checking source directory
      - pwd
      - ls -la
      - ls -la application

      - echo Building Docker image
      - docker build -t nginx-app ./application

      - echo Tagging Docker image
      - docker tag nginx-app:latest $ECR_REPOSITORY_URI:latest

      - echo Creating Elastic Beanstalk deployment file
      - |
        cat > application/Dockerrun.aws.json <<EOF
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "$ECR_REPOSITORY_URI:latest",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": "80"
            }
          ]
        }
        EOF

      - echo Creating deployment zip
      - cd application
      - zip deploy.zip Dockerrun.aws.json
      - cd ..

  post_build:
    commands:
      - echo Pushing Docker image to ECR
      - docker push $ECR_REPOSITORY_URI:latest

artifacts:
  files:
    - application/deploy.zip
