version: 0.2

phases:
  install:
    commands:
      - echo "Starting deployment"
      - terraform version

  pre_build:
    commands:
      - cd terraform
      - terraform init

  build:
    commands:
      - terraform plan -out=tfplan

  post_build:
    commands:
      - terraform apply -auto-approve tfplan