version: 0.2

phases:

  install:
    commands:
      - echo Installing Terraform
      - curl -fsSL https://releases.hashicorp.com/terraform/1.14.4/terraform_1.14.4_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/

      - echo Checking Terraform
      - terraform version

      - echo Checking Docker
      - docker version


  pre_build:
    commands:
      - echo Starting Terraform validation


  build:
    commands:

      - echo Testing Terraform
      - cd terraform
      - terraform init -backend=false
      - terraform validate
      - cd ..

      - echo Building Docker image
      - docker build -t nginx-test ./application

      - echo Running NGINX container
      - docker run -d -p 8080:80 --name nginx-test nginx-test

      - sleep 5

      - echo Testing website
      - curl http://localhost:8080


  post_build:
    commands:
      - echo Cleaning up container
      - docker stop nginx-test || true
      - docker rm nginx-test || true